-- 테스트를 위해 RLS 임시 비활성화
-- 주의: 프로덕션에서는 절대 사용하지 마세요!

ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE zone_leaders DISABLE ROW LEVEL SECURITY;
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE referrals DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE points DISABLE ROW LEVEL SECURITY;
ALTER TABLE devices DISABLE ROW LEVEL SECURITY;

-- 확인 메시지
SELECT 'RLS가 비활성화되었습니다. 테스트 후 다시 활성화하세요!' as message;
